version : '3.8'

services:

  poke-api:
    container_name: poke-api
    build: .
    restart: always
    expose:
      - 3000
  
  nginx:
    image: nginx:stable-alpine
    restart: always
    expose:
      - 80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=pokemon.sebastianreyes.cl,www.pokemon.sebastianreyes.cl
      - LETSENCRYPT_HOST=pokemon.sebastianreyes.cl,www.pokemon.sebastianreyes.cl
      - LETSENCRYPT_EMAIL=hola@sebastianreyes.cl

networks:
  default:
    external:
      name: main